### ISSUE TITLE
Call to undefined function Blinq\Synth\pcntl_signal()

### ISSUE THREAD

**Issue by tauseedzaman** [blinq-dev/laravel-synth#4]
### What happened?

HI
i just installed this package on my test project and when i run 
`php artisan synth` 
i get this error

![image](https://github.com/blinq-dev/laravel-synth/assets/64689921/8c9d60ce-27b9-4663-bfba-794a5ede7dd1)

### How to reproduce the bug

i just executed 
php artisan synth

### Package Version

2.0

### PHP Version

8.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

### Notes

i just install the package put my key and env and executed php artisan synth and got that error

**Comment by lennardv2** [comment]
I think you are missing the php pcntl extension, which is not available for windows i think.
